version: "3"
services:
  db:
    image: mariadb:10.3
    environment:
      MYSQL_DATABASE: "temp"
      MYSQL_ROOT_PASSWORD: "PASSWORD"
    ports:
      - "3306:3306"
    volumes:
      - ./temp_db.sql:/docker-entrypoint-initdb.d/dump.sql
  server:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    env_file:
      - .env
    links:
      - db
    volumes:
      - /home/player1/Documents/Content/coding_projects/budget_tracker_website_react_apollo/server/src:/usr/src/app/src
    command: npm start
  client:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    env_file:
      - .env
    links:
      - server
    volumes:
      - /home/player1/Documents/Content/coding_projects/budget_tracker_website_react_apollo/client/src:/usr/src/app/src
    command: npm start