version: "3"
services:
  db:
    image: mariadb:10.3
    environment:
      MYSQL_DATABASE: "budget_tracker"
      MYSQL_ROOT_PASSWORD: "PASSWORD"
    ports:
      - "3306:3306"
    volumes:
      - ./sample_dump.sql:/docker-entrypoint-initdb.d/dump.sql
  server:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    env_file:
      - .env
    links:
      - db
    # Update these local mount points for your local location
    volumes:
      - /home/player1/Content/coding_projects/example_react_apollo_webstack/server/src:/usr/src/app/src
    command: npm start
  client:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    env_file:
      - .env
    links:
      - server
    volumes:
      - /home/player1/Content/coding_projects/example_react_apollo_webstack/client/src:/usr/src/app/src
    command: npm start
